2017-03-19 13:13:57,901 [Thread-10:13732] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-19 13:14:02,411 [Thread-11:5052] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/
2017-03-19 13:16:42,201 [Thread-7:12764] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/
2017-03-19 13:16:43,086 [Thread-8:13332] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:16:44,744 [Thread-9:13396] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:16:57,937 [Thread-13:12896] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:16:59,464 [Thread-14:5404] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:17:01,460 [Thread-15:3888] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:17:04,844 [Thread-16:7136] [django.request:182] [base:get_response] [WARNING]- Not Found: /
2017-03-19 13:17:14,381 [Thread-7:12216] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 13, in get
    return render(request, "login.html", {'login_form': login_form})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 13:39:14,384 [Thread-7:11048] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 21, in get
    return render(request, "login.html", {'login_form': login_form, 'has_superuser':has_superuser})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'register' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 13:39:53,835 [Thread-13:14008] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 21, in get
    return render(request, "login.html", {'login_form': login_form, 'has_superuser':has_superuser})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'register' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 13:39:56,233 [Thread-14:13756] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 21, in get
    return render(request, "login.html", {'login_form': login_form, 'has_superuser':has_superuser})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'register' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 14:06:12,043 [Thread-42:13836] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 72, in post
    staff.save()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\base_user.py", line 74, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\models\sql\compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: NOT NULL constraint failed: company_staff.birthday
2017-03-19 14:17:53,687 [Thread-8:13244] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 46, in get
    return render(request, 'regist.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for '/' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 14:20:36,313 [Thread-7:6672] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 17, in get
    login_form = LoginForm()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:20:49,286 [Thread-11:4976] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 17, in get
    login_form = LoginForm()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:23:14,634 [Thread-14:10596] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 17, in get
    if Staff.objects.filter(is_superuser=True):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:24:01,322 [Thread-8:12596] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 24, in post
    login_form = LoginForm(request.POST)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:24:20,732 [Thread-9:5728] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 24, in post
    login_form = LoginForm(request.POST)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:24:55,319 [Thread-14:11212] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 24, in post
    login_form = LoginForm(request.POST)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:25:57,852 [Thread-8:13780] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 24, in post
    login_form = LoginForm(request.POST)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:27:42,428 [Thread-12:13772] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 24, in post
    login_form = LoginForm(request.POST)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\forms\models.py", line 275, in __init__
    raise ValueError('ModelForm has no model class specified.')
ValueError: ModelForm has no model class specified.
2017-03-19 14:28:08,661 [Thread-9:6428] [django.request:182] [base:get_response] [WARNING]- Not Found: /index
2017-03-19 14:28:39,026 [Thread-14:3824] [django.request:182] [base:get_response] [WARNING]- Not Found: /index
2017-03-19 17:28:22,407 [Thread-7:6472] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/
2017-03-19 17:28:25,595 [Thread-9:12832] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\python_env\dssms\apps\company\views.py", line 40, in post
    render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'all_staffs' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-19 17:29:50,480 [Thread-12:12444] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view company.views.LoginView didn't return an HttpResponse object. It returned None instead.
2017-03-19 17:30:54,039 [Thread-7:6140] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:32:14,180 [Thread-66:13076] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:35:05,029 [Thread-88:12332] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:35:20,631 [Thread-95:14280] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:38:10,638 [Thread-110:12708] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:38:36,543 [Thread-117:4292] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:39:59,528 [Thread-128:6816] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:45:52,878 [Thread-142:2096] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 17:57:13,288 [Thread-8:8112] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-19 20:54:30,135 [Thread-8:900] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-19 20:55:56,809 [Thread-7:4644] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /
2017-03-19 20:56:01,888 [Thread-10:6228] [django.request:94] [base:http_method_not_allowed] [WARNING]- Method Not Allowed (GET): /logout/
2017-03-19 21:04:07,697 [Thread-9:6964] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /logout/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view company.views.LogoutView didn't return an HttpResponse object. It returned None instead.
2017-03-19 21:42:50,278 [Thread-10:7880] [django.request:182] [base:get_response] [WARNING]- Not Found: /index
2017-03-19 22:53:58,697 [Thread-9:3328] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/
2017-03-20 09:32:03,803 [Thread-8:3856] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-20 10:35:16,578 [Thread-7:7936] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 15, in get
    return render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 10:36:29,451 [Thread-7:11112] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 17, in get
    return render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs?department=' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-20 10:36:46,022 [Thread-11:10536] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 17, in get
    return render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 10:37:26,578 [Thread-7:1120] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 17, in get
    return render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs/' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-20 10:37:35,855 [Thread-10:10924] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 17, in get
    return render(request, 'index.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs/' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-20 11:44:47,944 [Thread-12:6704] [django.request:182] [base:get_response] [WARNING]- Not Found: /index、
2017-03-20 12:37:01,239 [Thread-11:2612] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2017-03-20 12:38:29,058 [Thread-21:6908] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 12:38:30,043 [Thread-22:10248] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 12:38:30,816 [Thread-23:5248] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 12:38:40,351 [Thread-24:9096] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 12:38:55,953 [Thread-26:6140] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs/' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-20 12:50:05,525 [Thread-70:6076] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /index/staffs//
2017-03-20 12:53:40,540 [Thread-83:2432] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/staffs/(?P<department>.*)/']
2017-03-20 12:54:03,796 [Thread-86:6984] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department+'人员', 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'staffs/' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-20 12:59:13,948 [Thread-11:1008] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/staffs/
2017-03-20 12:59:36,842 [Thread-15:5144] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/staffs/
2017-03-20 14:25:38,523 [Thread-7:1324] [django.request:182] [base:get_response] [WARNING]- Not Found: /login/
2017-03-20 14:25:38,571 [Thread-8:9496] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-20 14:52:52,043 [Thread-7:4980] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'department':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 18: 'endif', expected 'else' 或 'endifequal'. Did you forget to register or load this tag?
2017-03-20 16:21:35,397 [Thread-28:8484] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/领导/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'deptname':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '|' from '|'
2017-03-20 16:21:46,990 [Thread-34:9004] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/领导/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'deptname':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid filter: 'gt'
2017-03-20 16:28:46,839 [Thread-7:7328] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/领导/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'deptname':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'greatherthan' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
future
i18n
l10n
log
static
staticfiles
tz
xadmin_tags
2017-03-20 23:22:56,072 [Thread-7:3868] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'deptname':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: ''greatherthen'' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
future
i18n
l10n
log
static
staticfiles
tz
xadmin_tags
2017-03-20 23:27:31,532 [Thread-7:11512] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/staffs/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 38, in get
    return render(request, 'staffs.html', {'staffs':staffs, 'deptname':department, 'departments':departments})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: ''greatherthen'' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
future
i18n
l10n
log
static
staticfiles
tz
xadmin_tags
2017-03-21 09:49:42,628 [Thread-19:1728] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-21 15:25:38,257 [Thread-8:9140] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty//
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'value'
2017-03-21 15:25:51,121 [Thread-13:13196] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty//
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'value'
2017-03-21 15:26:32,391 [Thread-20:12112] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'value'
2017-03-21 15:27:03,173 [Thread-7:11688] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'add_duties' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-21 15:27:27,704 [Thread-13:12732] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'add_duties' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-21 15:27:39,042 [Thread-19:3004] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'add_duties' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-21 23:49:55,881 [Thread-8:10340] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-22 16:43:38,463 [Thread-8:6864] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-22 16:43:43,263 [Thread-53:7784] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'add_duties' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-22 16:49:54,371 [Thread-73:11516] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'add_duties' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-03-22 16:59:02,255 [Thread-7:7784] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 101, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 513, in render
    six.reraise(*exc_info)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\defaulttags.py", line 499, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'depart_duty' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: ['index/depart_duty/(?P<value>.*)$']
2017-03-22 17:13:59,451 [Thread-12:2880] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /index/depart_duty/?
2017-03-22 17:14:04,496 [Thread-13:10744] [django.request:103] [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /index/depart_duty/?
2017-03-22 17:29:54,769 [Thread-15:11808] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/?
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: post() got an unexpected keyword argument 'value'
2017-03-22 17:30:42,142 [Thread-20:12292] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/?
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
TypeError: post() got an unexpected keyword argument 'value'
2017-03-22 17:34:01,589 [Thread-10:3024] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/?/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 158, in get_response
    % (callback.__module__, view_name))
ValueError: The view operations.views.DepartDutyView didn't return an HttpResponse object. It returned None instead.
2017-03-23 11:26:00,124 [Thread-19:2268] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-23 15:19:07,635 [Thread-16:4084] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/depart_duty/
2017-03-23 15:27:49,365 [Thread-8:8864] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:49,546 [Thread-9:7608] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:49,760 [Thread-10:1468] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:49,938 [Thread-11:9332] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:51,046 [Thread-12:2776] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/人力资源/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:52,039 [Thread-13:3880] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/领导/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:56,687 [Thread-14:7688] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:27:57,579 [Thread-15:4772] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/人力资源/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:28:00,806 [Thread-16:6088] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: u'ifequal' takes two arguments
2017-03-23 15:33:55,362 [Thread-35:7588] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/设计/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 102, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '["Department"]' from 'dept["Department"]'
2017-03-24 09:25:21,052 [Thread-8:11088] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-24 09:25:26,082 [Thread-53:780] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 99, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
2017-03-24 09:26:51,203 [Thread-54:4112] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/所有/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 99, in get
    return render(request, 'add_duty.html', {})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Invalid block tag on line 4: 'static', expected 'endblock'. Did you forget to register or load this tag?
2017-03-24 09:32:09,428 [Thread-8:10912] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-24 09:43:36,756 [Thread-40:10300] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/depart_duty
2017-03-24 09:43:40,762 [Thread-41:10244] [django.request:182] [base:get_response] [WARNING]- Not Found: /index/depart_duty/
2017-03-24 14:16:09,306 [Thread-8:8992] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-24 23:23:52,655 [Thread-8:5172] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-24 23:43:58,907 [Thread-34:876] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/depart_duty/?/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:/python_env/dssms\utils\mixin_utils.py", line 10, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 127, in post
    duty.department = departs[0]
TypeError: 'Department' object does not support indexing
2017-03-25 21:21:13,006 [Thread-19:12412] [django.request:182] [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-03-25 21:21:17,154 [Thread-26:11868] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/departs_dutys/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 165, in get
    dutys = p.page(page)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\pure_pagination\paginator.py", line 54, in page
    return Page(self.object_list[bottom:top], number, self)
TypeError: unhashable type
2017-03-25 21:31:55,124 [Thread-7:12672] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/departs_dutys/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 165, in get
    dutys = p.page(page)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\pure_pagination\paginator.py", line 54, in page
    return Page(self.object_list[bottom:top], number, self)
TypeError: unhashable type
2017-03-25 21:34:59,877 [Thread-13:4940] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/departs_dutys/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 165, in get
    dutys = p.page(page)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\pure_pagination\paginator.py", line 54, in page
    return Page(self.object_list[bottom:top], number, self)
TypeError: unhashable type
2017-03-25 23:03:07,256 [Thread-7:12492] [django.request:284] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /index/departs_dutys/
Traceback (most recent call last):
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:/python_env/dssms\operations\views.py", line 167, in get
    return render(request, 'depts_dutys.html', {"dutys": dutys})
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 231, in compile_nodelist
    return parser.parse()
  File "D:\python_env\dssms_env_for_win\lib\site-packages\django\template\base.py", line 516, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '()' from 'Department()'
